cloud:
  aws:
    pinpoint:
      appId: 16b0385f0ff74d29abfd7c7108c6cab3
      accessKeyId: AKIARBBZT4F7HJUXTLXE
      secretKey: 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
      emailFrom: mega.bytes.test.email@gmail.com
      smsFrom: 18336160067
      smsSenderId: MegaBytes

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka

megabytes:
  frontend:
    address: http://localhost:3000

spring:
  datasource:
    url: jdbc:mysql://megabytes.cqx2qps0orpk.us-east-1.rds.amazonaws.com:3306/capstone
    username: admin
    password: CWWfj73N92fFUNMPnHds
  jpa:
    show-sql: true
